// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptsbnywxgfgvmhhxszcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0c2JueXd4Z2Zndm1oaHhzemNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MTU0NzUsImV4cCI6MjA1NjM5MTQ3NX0.pRYjmxro6gCzJ4d-h92YacRO4-hw_3KSTemHf6tcyws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);